// API and storage constants

export const API_BASE_URL = 'http://localhost:5000/api';

export const STORAGE_KEYS = {
  AUTH_TOKEN: 'hermex_auth_token',
  API_URL: 'hermex_api_url',
  ACTIVE_SESSION: 'hermex_active_session',
};

export const MSG = {
  // Auth
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_REGISTER: 'AUTH_REGISTER',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_STATUS: 'AUTH_STATUS',
  UPDATE_PROFILE: 'UPDATE_PROFILE',

  // Sessions
  CREATE_SESSION: 'CREATE_SESSION',
  GET_SESSION: 'GET_SESSION',
  LIST_SESSIONS: 'LIST_SESSIONS',
  DELETE_SESSION: 'DELETE_SESSION',
  END_SESSION: 'END_SESSION',
  SESSION_CREATED: 'SESSION_CREATED',

  // UI
  OPEN_SIDE_PANEL: 'OPEN_SIDE_PANEL',

  // Checkpoints
  ANSWER_CHECKPOINT: 'ANSWER_CHECKPOINT',
  CHECKPOINT_TRIGGERED: 'CHECKPOINT_TRIGGERED',

  // Chat
  SEND_CHAT: 'SEND_CHAT',

  // Study Materials
  GENERATE_MATERIALS: 'GENERATE_MATERIALS',
  LIST_MATERIALS: 'LIST_MATERIALS',
  GET_MATERIAL: 'GET_MATERIAL',

  // Recap
  GET_RECAP: 'GET_RECAP',
  GENERATE_RECAP: 'GENERATE_RECAP',

  // Player
  GET_CURRENT_TIME: 'GET_CURRENT_TIME',
  GET_VIDEO_INFO: 'GET_VIDEO_INFO',

  // Learning Profile
  GET_LEARNING_PROFILE: 'GET_LEARNING_PROFILE',
  UPDATE_LEARNING_PROFILE: 'UPDATE_LEARNING_PROFILE',
  GET_LEARNING_CONTEXT: 'GET_LEARNING_CONTEXT',
  UPDATE_LEARNING_CONTEXT: 'UPDATE_LEARNING_CONTEXT',
};
